# Nixpacks config for Laravel on Railway
# - Installs PHP deps and builds Vite assets
# - Serves Laravel via artisan on the provided PORT

[phases.install]
cmds = [
  "composer install --no-dev --prefer-dist --no-interaction --optimize-autoloader",
  "npm ci --no-audit --progress=false || npm install"
]

[phases.build]
cmds = [
  "npm run build",
  "php artisan config:cache",
  "php artisan route:cache",
  "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && php artisan storage:link || true && chmod -R 775 storage bootstrap/cache || true && php artisan serve --host 0.0.0.0 --port ${PORT}"
